<?php

namespace Lcb\VitrineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MeubleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeubleRepository extends EntityRepository
{
}
