lcb_accueil:
    path:     /
    defaults: { _controller: LcbVitrineBundle:Default:accueil }

lcb_news:
    path:     /news
    defaults: { _controller: LcbVitrineBundle:Default:news }

lcb_new:
    path:     /new/{id}
    defaults: { _controller: LcbVitrineBundle:Default:new }

lcb_projet:
    path:     /projet
    defaults: { _controller: LcbVitrineBundle:Default:projet }

lcb_boutique:
    path:     /boutique
    defaults: { _controller: LcbVitrineBundle:Default:boutique }

lcb_batars:
    path:     /les_batars
    defaults: { _controller: LcbVitrineBundle:Default:batars }

lcb_soute:
    path:     /la_soute
    defaults: {_controller: LcbVitrineBundle:Default:soute }

lcb_photos:
    path:     /photos
    defaults: { _controller: LcbVitrineBundle:Default:photos }

lcb_article:
    path:     /article/{id}
    defaults: { _controller: LcbVitrineBundle:Default:photos }

lcb_contact:
    path:     /contact
    defaults: { _controller: LcbVitrineBundle:Default:contact }

lcb_messages:
    path:     /messages
    defaults: { _controller: LcbVitrineBundle:Default:messages }

lcb_ajoutArticle:
    path:     /ajout
    defaults: { _controller: LcbVitrineBundle:Default:ajoutArticle }

lcb_fiches:
    path:     /fiches
    defaults: { _controller: LcbVitrineBundle:Default:fiches }

lcb_ajoutFiche:
    path:     /ajoutFiches
    defaults: { _controller: LcbVitrineBundle:Default:ajoutFiches }

lcb_merci:
    path:     /merci
    defaults: { _controller: LcbVitrineBundle:Default:merci }

lcb_ajout_meuble:
    path:     /ajout_meuble
    defaults: { _controller: LcbVitrineBundle:Default:ajoutMeuble }